/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/layout/AppBar.vue')['default']
    AppMain: typeof import('./src/components/layout/AppMain.vue')['default']
    AppNavigation: typeof import('./src/components/layout/AppNavigation.vue')['default']
    CapacityAnalysis: typeof import('./src/components/schedule/form/CapacityAnalysis.vue')['default']
    ClassActions: typeof import('./src/components/classes/ClassActions.vue')['default']
    ClassDialog: typeof import('./src/components/classes/ClassDialog.vue')['default']
    ClassHeader: typeof import('./src/components/classes/ClassHeader.vue')['default']
    ClassManagement: typeof import('./src/components/classes/ClassManagement.vue')['default']
    ClassSelector: typeof import('./src/components/schedule/form/ClassSelector.vue')['default']
    ClassTable: typeof import('./src/components/classes/ClassTable.vue')['default']
    DataFlowDebug: typeof import('./src/components/debug/DataFlowDebug.vue')['default']
    DatePicker: typeof import('./src/components/schedule/form/DatePicker.vue')['default']
    EnhancedClassSelector: typeof import('./src/components/schedule/form/EnhancedClassSelector.vue')['default']
    EnhancedRoomSelector: typeof import('./src/components/schedule/form/EnhancedRoomSelector.vue')['default']
    ExamRoomActions: typeof import('./src/components/examRooms/ExamRoomActions.vue')['default']
    ExamRoomDialog: typeof import('./src/components/examRooms/ExamRoomDialog.vue')['default']
    ExamRoomHeader: typeof import('./src/components/examRooms/ExamRoomHeader.vue')['default']
    ExamRoomManagement: typeof import('./src/components/examRooms/ExamRoomManagement.vue')['default']
    ExamRoomStats: typeof import('./src/components/examRooms/ExamRoomStats.vue')['default']
    ExamRoomTable: typeof import('./src/components/examRooms/ExamRoomTable.vue')['default']
    ExcelImportDialog: typeof import('./src/components/classes/ExcelImportDialog.vue')['default']
    LanguageDistribution: typeof import('./src/components/schedule/form/LanguageDistribution.vue')['default']
    LanguageSelectionDebug: typeof import('./src/components/debug/LanguageSelectionDebug.vue')['default']
    NavigationDrawer: typeof import('./src/components/layout/NavigationDrawer.vue')['default']
    NavigationItem: typeof import('./src/components/layout/NavigationItem.vue')['default']
    RoomAssignmentCard: typeof import('./src/components/schedule/results/RoomAssignmentCard.vue')['default']
    RoomSelector: typeof import('./src/components/schedule/form/RoomSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleForm: typeof import('./src/components/schedule/ScheduleForm.vue')['default']
    ScheduleHeader: typeof import('./src/components/schedule/ScheduleHeader.vue')['default']
    ScheduleManagement: typeof import('./src/components/schedule/ScheduleManagement.vue')['default']
    ScheduleOptions: typeof import('./src/components/schedule/form/ScheduleOptions.vue')['default']
    ScheduleResults: typeof import('./src/components/schedule/ScheduleResults.vue')['default']
    ScheduleResultsHeader: typeof import('./src/components/schedule/results/ScheduleResultsHeader.vue')['default']
    ScheduleSummary: typeof import('./src/components/schedule/results/ScheduleSummary.vue')['default']
    SelectionDialog: typeof import('./src/components/schedule/form/SelectionDialog.vue')['default']
    SelectionDialogDemo: typeof import('./src/components/demo/SelectionDialogDemo.vue')['default']
    SessionSelector: typeof import('./src/components/schedule/form/SessionSelector.vue')['default']
    StudentChips: typeof import('./src/components/classes/StudentChips.vue')['default']
    StudentForm: typeof import('./src/components/classes/StudentForm.vue')['default']
  }
}
