/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClassCrud: typeof import('./src/components/ClassCrud.vue')['default']
    ExamRoomCrud: typeof import('./src/components/ExamRoomCrud.vue')['default']
    RoomSchedule: typeof import('./src/components/RoomSchedule.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
